/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "common_msg.pb-c.h"
void   pluse__init
                     (Pluse         *message)
{
  static Pluse init_value = PLUSE__INIT;
  *message = init_value;
}
size_t pluse__get_packed_size
                     (const Pluse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pluse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pluse__pack
                     (const Pluse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pluse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pluse__pack_to_buffer
                     (const Pluse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pluse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pluse *
       pluse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pluse *)
     protobuf_c_message_unpack (&pluse__descriptor,
                                allocator, len, data);
}
void   pluse__free_unpacked
                     (Pluse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &pluse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_auth__init
                     (ReqAuth         *message)
{
  static ReqAuth init_value = REQ_AUTH__INIT;
  *message = init_value;
}
size_t req_auth__get_packed_size
                     (const ReqAuth *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_auth__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_auth__pack
                     (const ReqAuth *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_auth__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_auth__pack_to_buffer
                     (const ReqAuth *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_auth__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqAuth *
       req_auth__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqAuth *)
     protobuf_c_message_unpack (&req_auth__descriptor,
                                allocator, len, data);
}
void   req_auth__free_unpacked
                     (ReqAuth *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_auth__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ack_common__init
                     (AckCommon         *message)
{
  static AckCommon init_value = ACK_COMMON__INIT;
  *message = init_value;
}
size_t ack_common__get_packed_size
                     (const AckCommon *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_common__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ack_common__pack
                     (const AckCommon *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_common__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ack_common__pack_to_buffer
                     (const AckCommon *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_common__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AckCommon *
       ack_common__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AckCommon *)
     protobuf_c_message_unpack (&ack_common__descriptor,
                                allocator, len, data);
}
void   ack_common__free_unpacked
                     (AckCommon *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_common__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   task__desc__init
                     (TaskDesc         *message)
{
  static TaskDesc init_value = TASK__DESC__INIT;
  *message = init_value;
}
size_t task__desc__get_packed_size
                     (const TaskDesc *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task__desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t task__desc__pack
                     (const TaskDesc *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task__desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t task__desc__pack_to_buffer
                     (const TaskDesc *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task__desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaskDesc *
       task__desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaskDesc *)
     protobuf_c_message_unpack (&task__desc__descriptor,
                                allocator, len, data);
}
void   task__desc__free_unpacked
                     (TaskDesc *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &task__desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_set_config__init
                     (ReqSetConfig         *message)
{
  static ReqSetConfig init_value = REQ_SET_CONFIG__INIT;
  *message = init_value;
}
size_t req_set_config__get_packed_size
                     (const ReqSetConfig *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_set_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_set_config__pack
                     (const ReqSetConfig *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_set_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_set_config__pack_to_buffer
                     (const ReqSetConfig *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_set_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqSetConfig *
       req_set_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqSetConfig *)
     protobuf_c_message_unpack (&req_set_config__descriptor,
                                allocator, len, data);
}
void   req_set_config__free_unpacked
                     (ReqSetConfig *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_set_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_get_config__init
                     (ReqGetConfig         *message)
{
  static ReqGetConfig init_value = REQ_GET_CONFIG__INIT;
  *message = init_value;
}
size_t req_get_config__get_packed_size
                     (const ReqGetConfig *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_get_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_get_config__pack
                     (const ReqGetConfig *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_get_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_get_config__pack_to_buffer
                     (const ReqGetConfig *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_get_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqGetConfig *
       req_get_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqGetConfig *)
     protobuf_c_message_unpack (&req_get_config__descriptor,
                                allocator, len, data);
}
void   req_get_config__free_unpacked
                     (ReqGetConfig *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_get_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pluse__field_descriptors[1] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Pluse, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pluse__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange pluse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor pluse__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Pluse",
  "Pluse",
  "Pluse",
  "",
  sizeof(Pluse),
  1,
  pluse__field_descriptors,
  pluse__field_indices_by_name,
  1,  pluse__number_ranges,
  (ProtobufCMessageInit) pluse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_auth__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqAuth, timestamp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqAuth, auth_key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqAuth, sign),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_auth__field_indices_by_name[] = {
  1,   /* field[1] = auth_key */
  2,   /* field[2] = sign */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange req_auth__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor req_auth__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReqAuth",
  "ReqAuth",
  "ReqAuth",
  "",
  sizeof(ReqAuth),
  3,
  req_auth__field_descriptors,
  req_auth__field_indices_by_name,
  1,  req_auth__number_ranges,
  (ProtobufCMessageInit) req_auth__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ack_common__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckCommon, code),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckCommon, msg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ack_common__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = msg */
};
static const ProtobufCIntRange ack_common__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ack_common__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "AckCommon",
  "AckCommon",
  "AckCommon",
  "",
  sizeof(AckCommon),
  2,
  ack_common__field_descriptors,
  ack_common__field_indices_by_name,
  1,  ack_common__number_ranges,
  (ProtobufCMessageInit) ack_common__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor task__desc__field_descriptors[5] =
{
  {
    "task_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskDesc, task_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retcode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskDesc, retcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskDesc, result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str_result",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskDesc, str_result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TaskDesc, output),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned task__desc__field_indices_by_name[] = {
  4,   /* field[4] = output */
  2,   /* field[2] = result */
  1,   /* field[1] = retcode */
  3,   /* field[3] = str_result */
  0,   /* field[0] = task_id */
};
static const ProtobufCIntRange task__desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor task__desc__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Task_Desc",
  "TaskDesc",
  "TaskDesc",
  "",
  sizeof(TaskDesc),
  5,
  task__desc__field_descriptors,
  task__desc__field_indices_by_name,
  1,  task__desc__number_ranges,
  (ProtobufCMessageInit) task__desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_set_config__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqSetConfig, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqSetConfig, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_set_config__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange req_set_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor req_set_config__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReqSetConfig",
  "ReqSetConfig",
  "ReqSetConfig",
  "",
  sizeof(ReqSetConfig),
  2,
  req_set_config__field_descriptors,
  req_set_config__field_indices_by_name,
  1,  req_set_config__number_ranges,
  (ProtobufCMessageInit) req_set_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_get_config__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqGetConfig, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_get_config__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange req_get_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor req_get_config__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReqGetConfig",
  "ReqGetConfig",
  "ReqGetConfig",
  "",
  sizeof(ReqGetConfig),
  1,
  req_get_config__field_descriptors,
  req_get_config__field_indices_by_name,
  1,  req_get_config__number_ranges,
  (ProtobufCMessageInit) req_get_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
