/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "taskmsg.pb-c.h"
void   req_execute_task__init
                     (ReqExecuteTask         *message)
{
  static ReqExecuteTask init_value = REQ_EXECUTE_TASK__INIT;
  *message = init_value;
}
size_t req_execute_task__get_packed_size
                     (const ReqExecuteTask *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_execute_task__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_execute_task__pack
                     (const ReqExecuteTask *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_execute_task__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_execute_task__pack_to_buffer
                     (const ReqExecuteTask *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_execute_task__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqExecuteTask *
       req_execute_task__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqExecuteTask *)
     protobuf_c_message_unpack (&req_execute_task__descriptor,
                                allocator, len, data);
}
void   req_execute_task__free_unpacked
                     (ReqExecuteTask *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_execute_task__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_task_common__init
                     (ReqTaskCommon         *message)
{
  static ReqTaskCommon init_value = REQ_TASK_COMMON__INIT;
  *message = init_value;
}
size_t req_task_common__get_packed_size
                     (const ReqTaskCommon *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_task_common__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_task_common__pack
                     (const ReqTaskCommon *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_task_common__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_task_common__pack_to_buffer
                     (const ReqTaskCommon *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_task_common__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqTaskCommon *
       req_task_common__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqTaskCommon *)
     protobuf_c_message_unpack (&req_task_common__descriptor,
                                allocator, len, data);
}
void   req_task_common__free_unpacked
                     (ReqTaskCommon *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &req_task_common__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ack_task_output__init
                     (AckTaskOutput         *message)
{
  static AckTaskOutput init_value = ACK_TASK_OUTPUT__INIT;
  *message = init_value;
}
size_t ack_task_output__get_packed_size
                     (const AckTaskOutput *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ack_task_output__pack
                     (const AckTaskOutput *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ack_task_output__pack_to_buffer
                     (const AckTaskOutput *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AckTaskOutput *
       ack_task_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AckTaskOutput *)
     protobuf_c_message_unpack (&ack_task_output__descriptor,
                                allocator, len, data);
}
void   ack_task_output__free_unpacked
                     (AckTaskOutput *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ack_task_result__init
                     (AckTaskResult         *message)
{
  static AckTaskResult init_value = ACK_TASK_RESULT__INIT;
  *message = init_value;
}
size_t ack_task_result__get_packed_size
                     (const AckTaskResult *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ack_task_result__pack
                     (const AckTaskResult *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ack_task_result__pack_to_buffer
                     (const AckTaskResult *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AckTaskResult *
       ack_task_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AckTaskResult *)
     protobuf_c_message_unpack (&ack_task_result__descriptor,
                                allocator, len, data);
}
void   ack_task_result__free_unpacked
                     (AckTaskResult *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ack_task_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor req_execute_task__field_descriptors[2] =
{
  {
    "task_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqExecuteTask, task_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqExecuteTask, command),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_execute_task__field_indices_by_name[] = {
  1,   /* field[1] = command */
  0,   /* field[0] = task_id */
};
static const ProtobufCIntRange req_execute_task__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor req_execute_task__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReqExecuteTask",
  "ReqExecuteTask",
  "ReqExecuteTask",
  "",
  sizeof(ReqExecuteTask),
  2,
  req_execute_task__field_descriptors,
  req_execute_task__field_indices_by_name,
  1,  req_execute_task__number_ranges,
  (ProtobufCMessageInit) req_execute_task__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_task_common__field_descriptors[1] =
{
  {
    "task_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReqTaskCommon, task_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_task_common__field_indices_by_name[] = {
  0,   /* field[0] = task_id */
};
static const ProtobufCIntRange req_task_common__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor req_task_common__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReqTaskCommon",
  "ReqTaskCommon",
  "ReqTaskCommon",
  "",
  sizeof(ReqTaskCommon),
  1,
  req_task_common__field_descriptors,
  req_task_common__field_indices_by_name,
  1,  req_task_common__number_ranges,
  (ProtobufCMessageInit) req_task_common__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ack_task_output__field_descriptors[2] =
{
  {
    "req_result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckTaskOutput, req_result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckTaskOutput, output),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ack_task_output__field_indices_by_name[] = {
  1,   /* field[1] = output */
  0,   /* field[0] = req_result */
};
static const ProtobufCIntRange ack_task_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ack_task_output__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "AckTaskOutput",
  "AckTaskOutput",
  "AckTaskOutput",
  "",
  sizeof(AckTaskOutput),
  2,
  ack_task_output__field_descriptors,
  ack_task_output__field_indices_by_name,
  1,  ack_task_output__number_ranges,
  (ProtobufCMessageInit) ack_task_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ack_task_result__field_descriptors[3] =
{
  {
    "req_result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckTaskResult, req_result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "task_result",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckTaskResult, task_result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "task_str_result",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AckTaskResult, task_str_result),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ack_task_result__field_indices_by_name[] = {
  0,   /* field[0] = req_result */
  1,   /* field[1] = task_result */
  2,   /* field[2] = task_str_result */
};
static const ProtobufCIntRange ack_task_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ack_task_result__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "AckTaskResult",
  "AckTaskResult",
  "AckTaskResult",
  "",
  sizeof(AckTaskResult),
  3,
  ack_task_result__field_descriptors,
  ack_task_result__field_indices_by_name,
  1,  ack_task_result__number_ranges,
  (ProtobufCMessageInit) ack_task_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
